### ISSUE TITLE
Issue with ADC area calculation

### ISSUE THREAD

**Issue by tunghoang290780** [neurosim/DNN_NeuroSim_V2.1#1]
Hello,

In ProcessingUnit.cpp, the area of ADC per subarray is calculated using below equation
`areaResults.push_back(subArray->areaADC*(numSubArrayRow*numSubArrayCol));`
However, if `numColMuxed `is set to non-zero value (i.e. set to 8 or 8 bitlines share 1 ADC), the total area of ADC should be divided by `numColMuxed ` as below
`areaResults.push_back(subArray->areaADC*(numSubArrayRow*numSubArrayCol/numColMuxed));`

Am I missing some pieces?

Thanks
/T

**Comment by neurosim** [comment]
Hi, the "numSubArrayRow" and "numSubArrayCol" means the number of subarray in row and column (count vertically and horizontally) in each processing unit. For example, if "numSubArrayRow" and "numSubArrayCol" equals to 2, it means there are 2*2=4 subarrays in each processing unit.
The "subArray->areaADC" already takes consideration of "numColMuxed" in SubArray.cpp.

Thanks
