### ISSUE TITLE
Question about Amp latency calculation

### ISSUE THREAD

**Issue by ShawnHSH** [neurosim/DNN_NeuroSim_V2.1#3]
Hi! May I ask, why the latency in  MultilevelSenseAmp::CalculatePower is not the same with the readLatency calculated in MultilevelSenseAmp::CalculateLatency simulation? In CalculateLatency, readLatency = LatencyCol*numColMuxed, while CalculatePower only takes one LatencyCol. How is the energy consumption during the remaining (numColMuxed-1)*LatencyCol ? I'd appreciate it a lot if someone sheds a little light on it. :)
![Neurosim_latency_Q2_2 png](https://user-images.githubusercontent.com/43226705/112472281-e9699e00-8da7-11eb-8003-fc231b8cbbff.png)

![Neurosim_latency_Q2_1](https://user-images.githubusercontent.com/43226705/112472245-e078cc80-8da7-11eb-9742-a5ee8715d144.png)

**Comment by neurosim** [comment]
P_Col in CalculatePower function has counted the power of **all** columns consumed by ADC, so there is no need to consider the mux sharing again. In other words, here the energy consumption stays the same no matter the ADCs are shared or not.
