### ISSUE TITLE
The program is stuck on Estimation of Layer 1

### ISSUE THREAD

**Issue by conwaylee** [neurosim/DNN_NeuroSim_V2.1#5]
We use the DNN_NeuroSim_V2.0 programs, The steps are as follows:
1. make in NeuroSim folder using CMD in Ubuntu, we can find many .o files
2. Run train.py, the program is stuck on Estimation of Layer 1，no other logs.
Could you please help me? Thank you very much.
![image](https://user-images.githubusercontent.com/17800114/159957450-a21bc1fa-69e2-41fb-ae9f-7cc7e966d88f.png)

**Comment by ayushsrivastava01** [comment]
The same is happening with me

**Comment by conwaylee** [comment]
This is cause by gcc and g++ vision，using gcc 5 can solve the problem.

**Comment by ayushsrivastava01** [comment]
> This is cause by gcc and g++ vision，using gcc 5 can solve the problem. My - wechart is **a748506266**, neurosim fan can communicate with my by wechart.

Thanks Buddy.

**Comment by ayushsrivastava01** [comment]
> 

can you give your email-id please.
Thank You

**Comment by xianyi11** [comment]
I try to use gcc5 to solve this problem, it's work!!! But the installation of gcc5 is very diffcult for me '_'

**Comment by ghost** [comment]
Hello, I also encounter this problem but haven't solved it. May I ask you about the gcc5 installation, I try many ways but it still fails in Red Hat 8.5.0-16. My Wechart is KnightQQQ.

**Comment by xfong** [comment]
Simple fix:

Line 861 of ProcessingUnit.cpp and line 64 of ProcessingUnit.h: change "double GetWriteUpdateEstimation" to "void GetWriteUpdateEstimation"

Tested and works on Ubuntu 22.04 with gcc-11

**Comment by AseoShen** [comment]
It works for gcc 9 too! Thanks a lot


> Simple fix:
> 
> Line 861 of ProcessingUnit.cpp and line 64 of ProcessingUnit.h: change "double GetWriteUpdateEstimation" to "void GetWriteUpdateEstimation"
> 
> Tested and works on Ubuntu 22.04 with gcc-11
