### ISSUE TITLE
Question about weight update latency

### ISSUE THREAD

**Issue by fishfishfishfishfish** [neurosim/DNN_NeuroSim_V2.1#7]
When I set param->batchSize to 1, the result weight update latency become infns. I don't understand the relation between batch size and weight update. Could anyone please help me and explain? thanks.

**Comment by neurosim** [comment]
Hi! Because weights will be updated after every batch. So smaller batch size means more frequent weight updates ad consumes longer time.

**Comment by fishfishfishfishfish** [comment]
ok，I get it. Thanks!
